const airplanes = [
  {
    name: 'mustang',
    id: 'p-51d',
    fullName: 'P-51 Mustang',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Fighter',
    role: 'Escort Fighter',
    firstFlight: 1940,
    crew: 1,
    engineCount: 1,
    engine: 'Packard V-1650-7 Merlin',
    horsepower: 1695,
    topSpeed: 437,
    range: 1650,
    wingspan: 37,
    serviceCeiling: 41900
  },

  {
    name: 'superfortress',
    id: 'b-29',
    fullName: 'B-29 Superfortress',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Bomber',
    role: 'Strategic Bomber',
    firstFlight: 1942,
    crew: 11,
    engineCount: 4,
    engine: 'Wright R-3350',
    horsepower: 2200,
    topSpeed: 357,
    range: 3250,
    wingspan: 141,
    serviceCeiling: 31850
  },

  {
    name: 'spitfire',
    id: 'spitfire-mk9',
    fullName: 'Spitfire Mk IX',
    manufacturer: 'Supermarine',
    country: 'UK',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Rolls-Royce Merlin 61',
    horsepower: 1720,
    topSpeed: 408,
    range: 434,
    wingspan: 36.8,
    serviceCeiling: 43800
  },

  {
    name: 'bf109',
    id: 'bf-109g',
    fullName: 'Messerschmitt Bf 109 G',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'DB 605A',
    horsepower: 1455,
    topSpeed: 398,
    range: 528,
    wingspan: 32.5,
    serviceCeiling: 39000
  },

  {
    name: 'corsair',
    id: 'f4u-1d',
    fullName: 'F4U Corsair',
    manufacturer: 'Vought',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Multirole',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2250,
    topSpeed: 446,
    range: 1015,
    wingspan: 41,
    serviceCeiling: 41700
  },

  {
    name: 'thunderbolt',
    id: 'p-47d',
    fullName: 'P-47 Thunderbolt',
    manufacturer: 'Republic Aviation',
    country: 'USA',
    type: 'Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1941,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2300,
    topSpeed: 433,
    range: 1800,
    wingspan: 40.9,
    serviceCeiling: 43000
  },

  {
    name: 'zero',
    id: 'a6m2',
    fullName: 'A6M Zero',
    manufacturer: 'Mitsubishi',
    country: 'Japan',
    type: 'Fighter',
    role: 'Carrier Fighter',
    firstFlight: 1939,
    crew: 1,
    engineCount: 1,
    engine: 'Nakajima Sakae',
    horsepower: 940,
    topSpeed: 331,
    range: 1930,
    wingspan: 39.4,
    serviceCeiling: 33000
  },

  {
    name: 'flyingFortress',
    id: 'b-17g',
    fullName: 'B-17 Flying Fortress',
    manufacturer: 'Boeing',
    country: 'USA',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1935,
    crew: 10,
    engineCount: 4,
    engine: 'Wright R-1820',
    horsepower: 1200,
    topSpeed: 287,
    range: 2000,
    wingspan: 103.8,
    serviceCeiling: 35000
  },

  {
    name: 'lancaster',
    id: 'lancaster-b1',
    fullName: 'Avro Lancaster',
    manufacturer: 'Avro',
    country: 'UK',
    type: 'Bomber',
    role: 'Heavy Bomber',
    firstFlight: 1941,
    crew: 7,
    engineCount: 4,
    engine: 'Rolls-Royce Merlin XX',
    horsepower: 1280,
    topSpeed: 282,
    range: 2530,
    wingspan: 102,
    serviceCeiling: 24000
  },

  {
    name: 'me262',
    id: 'me-262a',
    fullName: 'Me 262',
    manufacturer: 'Messerschmitt',
    country: 'Germany',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 2,
    engine: 'Jumo 004',
    horsepower: null,
    topSpeed: 540,
    range: 652,
    wingspan: 41,
    serviceCeiling: 37500
  },

  {
    name: 'lightning',
    id: 'p-38',
    fullName: 'P-38 Lightning',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1939,
    crew: 1,
    engineCount: 2,
    engine: 'Allison V-1710',
    horsepower: 1600,
    topSpeed: 414,
    range: 1300,
    wingspan: 52,
    serviceCeiling: 44000
  },

  {
    name: 'bearcat',
    id: 'f8f',
    fullName: 'F8F Bearcat',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Fighter',
    role: 'Carrier Fighter',
    firstFlight: 1944,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney R-2800',
    horsepower: 2100,
    topSpeed: 421,
    range: 1105,
    wingspan: 35.5,
    serviceCeiling: 38800
  },

  {
    name: 'skyraider',
    id: 'a-1',
    fullName: 'A-1 Skyraider',
    manufacturer: 'Douglas',
    country: 'USA',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1945,
    crew: 1,
    engineCount: 1,
    engine: 'Wright R-3350',
    horsepower: 2700,
    topSpeed: 322,
    range: 1300,
    wingspan: 50,
    serviceCeiling: 28500
  },

  {
    name: 'hurricane',
    id: 'hurricane-mk1',
    fullName: 'Hawker Hurricane',
    manufacturer: 'Hawker',
    country: 'UK',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1935,
    crew: 1,
    engineCount: 1,
    engine: 'Rolls-Royce Merlin',
    horsepower: 1030,
    topSpeed: 340,
    range: 600,
    wingspan: 40,
    serviceCeiling: 36000
  },

  {
    name: 'tempest',
    id: 'tempest-v',
    fullName: 'Hawker Tempest',
    manufacturer: 'Hawker',
    country: 'UK',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Napier Sabre',
    horsepower: 2200,
    topSpeed: 432,
    range: 740,
    wingspan: 41,
    serviceCeiling: 37000
  },

  {
    name: 'mosquito',
    id: 'mosquito',
    fullName: 'De Havilland Mosquito',
    manufacturer: 'De Havilland',
    country: 'UK',
    type: 'Multirole',
    role: 'Bomber / Recon',
    firstFlight: 1940,
    crew: 2,
    engineCount: 2,
    engine: 'Rolls-Royce Merlin',
    horsepower: 1460,
    topSpeed: 415,
    range: 1500,
    wingspan: 54,
    serviceCeiling: 37000
  },

  {
    name: 'beaufighter',
    id: 'beaufighter',
    fullName: 'Bristol Beaufighter',
    manufacturer: 'Bristol',
    country: 'UK',
    type: 'Heavy Fighter',
    role: 'Night Fighter',
    firstFlight: 1939,
    crew: 2,
    engineCount: 2,
    engine: 'Bristol Hercules',
    horsepower: 1735,
    topSpeed: 320,
    range: 1750,
    wingspan: 57,
    serviceCeiling: 29000
  },

  {
    name: 'fw190',
    id: 'fw-190',
    fullName: 'Fw 190',
    manufacturer: 'Focke-Wulf',
    country: 'Germany',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1939,
    crew: 1,
    engineCount: 1,
    engine: 'BMW 801',
    horsepower: 1700,
    topSpeed: 408,
    range: 500,
    wingspan: 34.5,
    serviceCeiling: 37000
  },

  {
    name: 'mig15',
    id: 'mig-15',
    fullName: 'MiG-15',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1947,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-1',
    horsepower: null,
    topSpeed: 668,
    range: 745,
    wingspan: 33,
    serviceCeiling: 51000
  },

  {
    name: 'mig21',
    id: 'mig-21',
    fullName: 'MiG-21',
    manufacturer: 'Mikoyan-Gurevich',
    country: 'USSR',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'Tumansky R-25',
    horsepower: null,
    topSpeed: 1386,
    range: 760,
    wingspan: 23.5,
    serviceCeiling: 59000
  },

  {
    name: 'mig29',
    id: 'mig-29',
    fullName: 'MiG-29',
    manufacturer: 'Mikoyan',
    country: 'Russia',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1977,
    crew: 1,
    engineCount: 2,
    engine: 'RD-33',
    horsepower: null,
    topSpeed: 1490,
    range: 890,
    wingspan: 37,
    serviceCeiling: 59000
  },

  {
    name: 'su27',
    id: 'su-27',
    fullName: 'Su-27',
    manufacturer: 'Sukhoi',
    country: 'Russia',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1977,
    crew: 1,
    engineCount: 2,
    engine: 'AL-31F',
    horsepower: null,
    topSpeed: 1550,
    range: 2200,
    wingspan: 48,
    serviceCeiling: 62000
  },

  {
    name: 'phantom',
    id: 'f-4',
    fullName: 'F-4 Phantom II',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1958,
    crew: 2,
    engineCount: 2,
    engine: 'J79',
    horsepower: null,
    topSpeed: 1473,
    range: 1600,
    wingspan: 38.5,
    serviceCeiling: 60000
  },

  {
    name: 'tomcat',
    id: 'f-14',
    fullName: 'F-14 Tomcat',
    manufacturer: 'Grumman',
    country: 'USA',
    type: 'Fighter',
    role: 'Fleet Defense',
    firstFlight: 1970,
    crew: 2,
    engineCount: 2,
    engine: 'TF30 / F110',
    horsepower: null,
    topSpeed: 1544,
    range: 1800,
    wingspan: 64,
    serviceCeiling: 53000
  },

  {
    name: 'eagle',
    id: 'f-15',
    fullName: 'F-15 Eagle',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1972,
    crew: 1,
    engineCount: 2,
    engine: 'F100',
    horsepower: null,
    topSpeed: 1650,
    range: 3000,
    wingspan: 42.8,
    serviceCeiling: 65000
  },

  {
    name: 'falcon',
    id: 'f-16',
    fullName: 'F-16 Fighting Falcon',
    manufacturer: 'General Dynamics',
    country: 'USA',
    type: 'Fighter',
    role: 'Multirole',
    firstFlight: 1974,
    crew: 1,
    engineCount: 1,
    engine: 'F110',
    horsepower: null,
    topSpeed: 1500,
    range: 2600,
    wingspan: 32.8,
    serviceCeiling: 50000
  },

  {
    name: 'hornet',
    id: 'fa-18',
    fullName: 'F/A-18 Hornet',
    manufacturer: 'McDonnell Douglas',
    country: 'USA',
    type: 'Carrier Fighter',
    role: 'Multirole',
    firstFlight: 1978,
    crew: 1,
    engineCount: 2,
    engine: 'F404',
    horsepower: null,
    topSpeed: 1190,
    range: 1275,
    wingspan: 40.4,
    serviceCeiling: 50000
  },

  {
    name: 'yak3',
    id: 'yak-3',
    fullName: 'Yak-3',
    manufacturer: 'Yakovlev',
    country: 'USSR',
    type: 'Fighter',
    role: 'Air Superiority',
    firstFlight: 1943,
    crew: 1,
    engineCount: 1,
    engine: 'Klimov VK-105PF2',
    horsepower: 1290,
    topSpeed: 404,
    range: 404,
    wingspan: 30.2,
    serviceCeiling: 35300
  },

  {
    name: 'la5',
    id: 'la-5',
    fullName: 'Lavochkin La-5',
    manufacturer: 'Lavochkin',
    country: 'USSR',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1942,
    crew: 1,
    engineCount: 1,
    engine: 'Shvetsov ASh-82',
    horsepower: 1700,
    topSpeed: 404,
    range: 475,
    wingspan: 32.4,
    serviceCeiling: 36000
  },

  {
    name: 'il2',
    id: 'il-2',
    fullName: 'Il-2 Sturmovik',
    manufacturer: 'Ilyushin',
    country: 'USSR',
    type: 'Attack',
    role: 'Ground Attack',
    firstFlight: 1939,
    crew: 2,
    engineCount: 1,
    engine: 'Mikulin AM-38',
    horsepower: 1720,
    topSpeed: 257,
    range: 450,
    wingspan: 48,
    serviceCeiling: 19700
  },

  {
    name: 'pe2',
    id: 'pe-2',
    fullName: 'Petlyakov Pe-2',
    manufacturer: 'Petlyakov',
    country: 'USSR',
    type: 'Bomber',
    role: 'Dive Bomber',
    firstFlight: 1939,
    crew: 3,
    engineCount: 2,
    engine: 'Klimov VK-105',
    horsepower: 1100,
    topSpeed: 335,
    range: 720,
    wingspan: 57,
    serviceCeiling: 29000
  },

  {
    name: 'he162',
    id: 'he-162',
    fullName: 'Heinkel He 162',
    manufacturer: 'Heinkel',
    country: 'Germany',
    type: 'Jet Fighter',
    role: 'Interceptor',
    firstFlight: 1944,
    crew: 1,
    engineCount: 1,
    engine: 'BMW 003',
    horsepower: null,
    topSpeed: 562,
    range: 606,
    wingspan: 23.6,
    serviceCeiling: 39000
  },

  {
    name: 'do335',
    id: 'do-335',
    fullName: 'Dornier Do 335',
    manufacturer: 'Dornier',
    country: 'Germany',
    type: 'Heavy Fighter',
    role: 'Interceptor',
    firstFlight: 1943,
    crew: 1,
    engineCount: 2,
    engine: 'DB 603',
    horsepower: 1750,
    topSpeed: 474,
    range: 720,
    wingspan: 45,
    serviceCeiling: 37500
  },

  {
    name: 'sabre',
    id: 'f-86',
    fullName: 'F-86 Sabre',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Air Superiority',
    firstFlight: 1947,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric J47',
    horsepower: null,
    topSpeed: 687,
    range: 1515,
    wingspan: 37.1,
    serviceCeiling: 49000
  },

  {
    name: 'superSabre',
    id: 'f-100',
    fullName: 'F-100 Super Sabre',
    manufacturer: 'North American Aviation',
    country: 'USA',
    type: 'Jet Fighter',
    role: 'Fighter Bomber',
    firstFlight: 1953,
    crew: 1,
    engineCount: 1,
    engine: 'Pratt & Whitney J57',
    horsepower: null,
    topSpeed: 864,
    range: 1995,
    wingspan: 38.8,
    serviceCeiling: 50000
  },

  {
    name: 'starfighter',
    id: 'f-104',
    fullName: 'F-104 Starfighter',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Interceptor',
    role: 'High Speed Fighter',
    firstFlight: 1954,
    crew: 1,
    engineCount: 1,
    engine: 'General Electric J79',
    horsepower: null,
    topSpeed: 1456,
    range: 1630,
    wingspan: 21.9,
    serviceCeiling: 58000
  },

  {
    name: 'aardvark',
    id: 'f-111',
    fullName: 'F-111 Aardvark',
    manufacturer: 'General Dynamics',
    country: 'USA',
    type: 'Strike Aircraft',
    role: 'Ground Attack',
    firstFlight: 1964,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney TF30',
    horsepower: null,
    topSpeed: 1650,
    range: 3700,
    wingspan: 63,
    serviceCeiling: 60000
  },

  {
    name: 'mig23',
    id: 'mig-23',
    fullName: 'MiG-23',
    manufacturer: 'Mikoyan',
    country: 'USSR',
    type: 'Fighter',
    role: 'Interceptor',
    firstFlight: 1967,
    crew: 1,
    engineCount: 1,
    engine: 'Tumansky R-35',
    horsepower: null,
    topSpeed: 1550,
    range: 1150,
    wingspan: 45,
    serviceCeiling: 61000
  },

  {
    name: 'su25',
    id: 'su-25',
    fullName: 'Su-25 Frogfoot',
    manufacturer: 'Sukhoi',
    country: 'USSR',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1975,
    crew: 1,
    engineCount: 2,
    engine: 'Soyuz R-95',
    horsepower: null,
    topSpeed: 606,
    range: 465,
    wingspan: 47,
    serviceCeiling: 23000
  },

  {
    name: 'thunderboltII',
    id: 'a-10',
    fullName: 'A-10 Thunderbolt II',
    manufacturer: 'Fairchild Republic',
    country: 'USA',
    type: 'Attack',
    role: 'Close Air Support',
    firstFlight: 1972,
    crew: 1,
    engineCount: 2,
    engine: 'TF34',
    horsepower: null,
    topSpeed: 439,
    range: 800,
    wingspan: 57.5,
    serviceCeiling: 45000
  },

  {
    name: 'blackbird',
    id: 'sr-71',
    fullName: 'SR-71 Blackbird',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Reconnaissance',
    role: 'Strategic Recon',
    firstFlight: 1964,
    crew: 2,
    engineCount: 2,
    engine: 'Pratt & Whitney J58',
    horsepower: null,
    topSpeed: 2193,
    range: 3200,
    wingspan: 55.5,
    serviceCeiling: 85000
  },

  {
    name: 'dragonLady',
    id: 'u-2',
    fullName: 'U-2 Dragon Lady',
    manufacturer: 'Lockheed',
    country: 'USA',
    type: 'Reconnaissance',
    role: 'High Altitude Recon',
    firstFlight: 1955,
    crew: 1,
    engineCount: 1,
    engine: 'F118',
    horsepower: null,
    topSpeed: 500,
    range: 6900,
    wingspan: 104,
    serviceCeiling: 70000
  }
];
export default airplanes;
